### ISSUE TITLE
“如何修改sidebar中author的字体颜色”等问题

### ISSUE THREAD

**Issue by ooobug** [csuldw/FreeSky#1]
感谢博主的分享！主题很棒~
不过，在使用过程中发现一些小问题，但愿你可以帮助解决下~
1. sidebar中author的字体颜色为透明，无法直接看清（图1）；
2.  网站UV和PV数据为空（图2）；
3.  打开顶部栏Archives后，网页标题显示为Archive（是我调皮，不过这个确实是个小错误~）。
以上。

祝学习、工作顺利！

<img width="234" alt="qq 20190114180525" src="https://user-images.githubusercontent.com/35298968/51106766-b15d8c80-1827-11e9-967c-6a0baca586d3.png">
<img width="384" alt="qq 20190114180850" src="https://user-images.githubusercontent.com/35298968/51106771-b6224080-1827-11e9-8603-25e81f150bf5.png">

**Comment by csuldw** [comment]
访问量已修改 http://www.csuldw.com/2019/02/16/2019-02-16-notes/
